const logData = [
  {
    id: 1,
    level: 'warning',
    timeStamp: new Date('2026-02-10T10:15:00'),
    message: 'User input validation failed',
    source: '/app/controllers/userController.js',
    rawText: 'Validation error: missing required field "email"',
    stackTrace: null,
    exceptionType: null,
    exceptionMessage: null,
    processedTime: new Date('2026-02-10T10:16:00'),
  },
  {
    id: 2,
    level: 'error',
    timeStamp: new Date('2026-02-10T11:00:00'),
    message: 'Database connection failed',
    source: '/app/services/dbService.js',
    rawText: 'Error: Connection refused',
    stackTrace: 'at dbService.connect (/app/services/dbService.js:45:15)',
    exceptionType: 'System.Data.SqlClient.SqlException',
    exceptionMessage: 'Unable to connect to SQL Server',
    processedTime: new Date('2026-02-10T11:01:00'),
  },
  {
    id: 3,
    level: 'critical',
    timeStamp: new Date('2026-02-10T12:30:00'),
    message: 'Unhandled null reference exception',
    source: '/app/controllers/orderController.js',
    rawText: 'NullReferenceException: Object reference not set to an instance of an object',
    stackTrace: 'at orderController.createOrder (/app/controllers/orderController.js:78:20)',
    exceptionType: 'System.NullReferenceException',
    exceptionMessage: 'Object reference not set to an instance of an object',
    processedTime: new Date('2026-02-10T12:31:00'),
  },
  {
    id: 4,
    level: 'fatal',
    timeStamp: new Date('2026-02-10T14:45:00'),
    message: 'Application crash due to memory overflow',
    source: '/app/main.js',
    rawText: 'Fatal Error: Out of Memory',
    stackTrace: 'at main (/app/main.js:100:10)',
    exceptionType: 'System.OutOfMemoryException',
    exceptionMessage: 'Insufficient memory to continue the execution',
    processedTime: new Date('2026-02-10T14:46:00'),
  },
  {
    id: 5,
    level: 'warning',
    timeStamp: new Date('2026-02-11T08:20:00'),
    message: 'Slow API response detected',
    source: '/app/middleware/logMiddleware.js',
    rawText: 'API response time exceeded threshold: 3200ms',
    stackTrace: null,
    exceptionType: null,
    exceptionMessage: null,
    processedTime: new Date('2026-02-11T08:21:00'),
  },
  {
    id: 6,
    level: 'warning',
    timeStamp: new Date('2026-02-11T08:20:00'),
    message: 'Slow API response detected',
    source: '/app/middleware/logMiddleware.js',
    rawText: 'API response time exceeded threshold: 3200ms',
    stackTrace: null,
    exceptionType: null,
    exceptionMessage: null,
    processedTime: new Date('2026-02-11T08:21:00'),
  },
  {
    id: 7,
    level: 'warning',
    timeStamp: new Date('2026-02-11T08:20:00'),
    message: 'Slow API response detected',
    source: '/app/middleware/logMiddleware.js',
    rawText: 'API response time exceeded threshold: 3200ms',
    stackTrace: null,
    exceptionType: null,
    exceptionMessage: null,
    processedTime: new Date('2026-02-11T08:21:00'),
  },
  {
    id: 8,
    level: 'warning',
    timeStamp: new Date('2026-02-11T08:20:00'),
    message: 'Slow API response detected',
    source: '/app/middleware/logMiddleware.js',
    rawText: 'API response time exceeded threshold: 3200ms',
    stackTrace: null,
    exceptionType: null,
    exceptionMessage: null,
    processedTime: new Date('2026-02-11T08:21:00'),
  },
  {
    id: 9,
    level: 'warning',
    timeStamp: new Date('2026-02-11T08:20:00'),
    message: 'Slow API response detected',
    source: '/app/middleware/logMiddleware.js',
    rawText: 'API response time exceeded threshold: 3200ms',
    stackTrace: null,
    exceptionType: null,
    exceptionMessage: null,
    processedTime: new Date('2026-02-11T08:21:00'),
  },
  {
    id: 10,
    level: 'warning',
    timeStamp: new Date('2026-02-11T08:20:00'),
    message: 'Slow API response detected',
    source: '/app/middleware/logMiddleware.js',
    rawText: 'API response time exceeded threshold: 3200ms',
    stackTrace: null,
    exceptionType: null,
    exceptionMessage: null,
    processedTime: new Date('2026-02-11T08:21:00'),
  },
  {
    id: 11,
    level: 'warning',
    timeStamp: new Date('2026-02-11T08:20:00'),
    message: 'Slow API response detected',
    source: '/app/middleware/logMiddleware.js',
    rawText: 'API response time exceeded threshold: 3200ms',
    stackTrace: null,
    exceptionType: null,
    exceptionMessage: null,
    processedTime: new Date('2026-02-11T08:21:00'),
  },
  {
    id: 12,
    level: 'warning',
    timeStamp: new Date('2026-02-11T08:20:00'),
    message: 'Slow API response detected',
    source: '/app/middleware/logMiddleware.js',
    rawText: 'API response time exceeded threshold: 3200ms',
    stackTrace: null,
    exceptionType: null,
    exceptionMessage: null,
    processedTime: new Date('2026-02-11T08:21:00'),
  },
];

export default logData;
